version: "3.7"

services:
  node:
    working_dir: /app
    image: node:alpine3.12
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    command: "npm run dev"

  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"