version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: _docker/node/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./index.js:/home/node/app/index.js

  redis:
    image: redis:6.0.5-alpine
    ports:
      - "6379:6379"